pythonindia/inpycon-blog

content/blog/call-for-proposals-pycon-2015.md, content/blog/test.rst, publishconf.py, requirements.txt
- Add a blogpost for cfp.
- Remove test blog post.
- Add `markdown` as dependency.
- Update pelicanconf
=> Add CFP blog post

themes/inpycon/static/css/styles.css, themes/inpycon/templates/archives.html
=> Better looking archive.html

content/blog/poster_session_2015.md, content/blog/poster_session_2015.rst
This blog also contains inputs from Devyani Kota.
=> Added blog for poster presentation

content/blog/open-space-registrations.md
Added blog content for open space, please review and merge
@vnbang2003 @kracekumar
=> added blog content for openspace

content/blog/python_month_2016.md
=> Add Python month blog

content/blog/dev-sprints-announcement-2016.md
**Description:** Adding draft of Devsprint announcement for Pycon India 2016.
**Pending:**
* DevSprint Call for Proposal link.
* Adding images from previous year's Dev sprint
=> [DEVSPRINT ANNOUNCEMENT] Announcing DevSprint for Pycon India 2016.

content/blog/visible-alpha-gold-sponsor.md
Visible Alpha Gold Sponsor Blog Post
=> Visible Alpha Gold Sponsor Blog Post

content/blog/2017_cfp_announcement.md
=> PyCon India 2016 video link added

content/blog/travel-and-hotels-2017.md
The last blog about travel and accommodation during the conference was just a list of items which broke our feed fetcher on the in.pycon.org homepage. To keep it intact I've added one sentence which eventually makes a paragraph which can be read by the feed reader.
An alternate solution might have been modifying the feed reader which make take more time than just adding one more line to this blog hence I'm moving with this change.
Please review. cc: @akshayaurora @CuriousLearner
=> Minor-Fix to keep the xml feed running

content/blog/Announcing_keynote_speaker_forPyconIndia_2017_#3.md
Added blog post announcing the new keynote speaker Elizabeth Ferrao 
Added a few additional links. Do check.
=> Added blog post for keynote speaker #3 - Elizabeth Ferrao 

content/blog/travel-and-hotels-2017.md
New hotels added with addresses of all the other hotels.
Please review @akshayaurora @CuriousLearner
=> New hotels added with addresses

content/blog/Announcing_Pipal_Academy_as_the_Associate_Sponsor.md
In reference to issue #90 :hatching_chick:
Used the write-up as provided.
Some text formatting and hyperlinks in the text and image added pointing to https://pipal.in
Added some more links in the bottom ( their Contact Us, Github, twitter)
Review the content and do tell if something needs correction.
=> Announcing Associate Sponsor - Pipal Academy 

content/blog/community-participation-at-PyCon India-2017.md
I have added the blog for community spaces. The blog has been reviewed by some of the people at the volunteer channel. Please suggest further changes if required.
=> Added blog for community spaces

content/blog/Adobe-silver-sponsor.md, content/blog/Announcing_Pipal_Academy_as_the_Associate_Sponsor.md, content/blog/visible-alpha-gold-sponsor.md
=> Modified three blogs to fix the blog-feed

content/blog/community-participation-at-PyCon India-2017.md
=> Update community-participation-at-PyCon India-2017.md

content/blog/microsoft-platinum-sponsor.md
@realslimshanky need to replace the logo with better resolution one.
=> Adding blog for microsoft, our platinum sponsor.

themes/inpycon2017/static/css/styles.css
=> Fixing color schema of heading tag

content/blog/pycon-india-2018.rst
Signed-off-by: Sayan Chowdhury <sayan.chowdhury2012@gmail.com>
This fixes the rst syntax for the hyperlink and for blog. Note that the branch name is erroneous.
=> blog: Fix the issues in the PyCon India 2018 blog post

content/blog/pycon-india-2018-reschedule.md
Added Blog Post for Venue Reschedule and new date announcement
cc: @pythonindia/pycon-2018-team
=> Add blog post for Venue Reschedule Announcement

themes/inpycon2018/static/css/styles.css, themes/inpycon2018/templates/base.html
This PR is made in reference fixes #131.
Hover Effect :
- opacity:0.5;
- z-index:10;
=> [Added] Hover Effect on Social Media Icons.

content/blog/pycon-india-tickets-2018.md
- Added Blog for tickets sales. 
- Added a link to Convince My Boss in the same. 
- Solves #143 
**Note**
@ananyo2012 This needs to be updated constantly and we should add more details of the events as soon as it gets confirmed. 
@pythonindia/pycon-2018-team  Please review.
=> Add PyCon India Tickets blog

Pipfile, Pipfile.lock, README.md, requirements.txt
I have closed previous PR because I messed up commits and was not able to resolve the issue. I am still learning things. So I have create raise this new PR.
=> Add Pipfile and Pipfile.lock

content/blog/announcing_pramati_as_gold_sponsor.md
Please check and review. @ananyo2012
=> Announcing Pramati Technlogies as a Gold Sponsor

content/blog/announcing-go-jek-as-platinum-sponsor.md
Please Review and Merge.
Issue: #159
=> Announcing Go-Jek as a Platinum Sponsor

content/blog/pycon-india-tickets-2018.md
=> Changed ticket number to 350 in tickets blog

content/blog/understanding-dev-sprints-2018.md
Fixes #145 
@inovizz  Need some more information, mentioned it with capital letters.
@pythonindia/pycon-2018-team Review needed
=> Add Developer Sprints 2018 blog

themes/inpycon2018/templates/base.html
=> base.html : changed active class from Home to Blog

content/blog/2016-pycon-india-soon.md, content/blog/2016_cfp_dates.md, content/blog/2018_cfp_announcement.md, content/blog/announcing-keynote-speaker-for-pycon-india-2017-noufal.md, content/blog/open-space-registration-2016.md, content/blog/understanding-dev-sprints-2018.md
=> Multiple spell error fixes

content/blog/announcing-corteva-as-gold-sponsor.md
=> Adding corteva as gold sponser

content/blog/announcing-google-as-gold-sponsor.md
Update
Adding google as gold sponsor
=> Adding Google stuff

content/blog/announcing_zauba_as_gold_sponsor.md
=> Adding Zauba cloud as gold sponser

content/blog/announcing_vmware_as_gold_sponsor.md, content/blog/devsprints_2018_clarification.md
- [x ] Screenshots for changes (for bug fixes / features)
=> Blog for dev sprints queries clarification

themes/inpycon2019/templates/index.html
This is for the index page where we are listing only a portion of the
article. We would like to display are "Read More" link, so that people
know that there is more to read.
=> Add a link to make it more obvious that there is more to the article.

themes/inpycon2019/static/css/styles.css, themes/inpycon2019/templates/index.html
=> Fix image width; Add whitespace to separate content

pelicanconf.py, publishconf.py
Fix https://github.com/pythonindia/inpycon2019/issues/84
=> Use HTTPS URLs

content/blog/announcing-zeomega-DBS-as-silver-sponsors.md
=> Fix insecure img srcs

themes/inpycon2019/static/css/styles.css, themes/inpycon2019/templates/base.html
=> Sync navbar

content/blog/2019-convice-your-boss-with-this-email.md, content/blog/2019-making-pycon-india-accessible-first-step.md
* Adding convince my boss blogpost - courtesy Shalini.
* Adding a11y guide for PyCon India 2019.
=> Adding two articles from the diversity workgroup.

content/blog/understanding-the-devsprints-2019.md
=> added understanding the devsprints blog 2019

content/blog/2019-announcing-grofers-associate-sponsor.md
=> Update grofers content.

content/blog/2019-understanding-the-devsprints.md
=> Add devsprint proposal submission link

content/blog/2019-announcing-workshops.md
=> removes a workshop

content/blog/2020-call-for-proposals-announcement.md, content/blog/announcing-aqr-as-sponsor-2018.md, themes/inpycon2019/static/css/styles.css
Finally here, last review needed @sayanchowdhury @pythonindia/pycon-india-2020-infrastructure @ananyo2012 
Todo:
=> [2020] CFP Announcement Post 

themes/inpycon2020/templates/base.html
Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipul@balena.io>
=> Add COC in Navbar

content/blog/2020-call-for-proposals-announcement.md, content/blog/2020-workshop-call-for-proposals.md
Reviews needed @pythonindia/pycon-india-content-team @Pradhvan @ananyo2012 
Came up with this using PyCon US's Tutorials CFP as an inspiration. Please do read it once. 
Thanks
=> Add Editorial for Workshop CFP

content/blog/2020-volunteering.md
Blog Content
I've added a new blog post for the Call for Volunteers. It's a little lengthier than the previous year blogs, but it's still about a 5 min read. 
Please review. 
CC: @vipulgupta2048
=> Added 2020 Call for Volunteers Blog

Makefile, netlify.toml
Feature
Currently, the build commands don't install dependencies
Please have a look at the commit messages for more information.
=> Add build and deploy helpers

content/blog/2020-pycon-india-mentorship.md
Solves https://github.com/pythonindia/inpycon2020-tasks/issues/61
=> Added blog for mentorship 

content/blog/2020-outreach-partners.md
I've added the blog for Outreach Partners. 
- Is there anything that needs to be added/changed?
- Still need a contact link here. 
- Also, the About Us page needs to be deployed before merging this, as that link is currently not working. 
CC: @vipulgupta2048 @abhishekmishragithub
=> Outreach Partners blog

pelicanconf.py
Add pagination support
No Pagination
Index is paginated with 5 articles per page
=> Add pagination support

README.md, content/blog/2020-call-for-proposals-announcement.md, content/blog/2020-outreach-partners.md, content/blog/2020-pycon-india-mentorship.md, content/blog/2020-volunteering.md, content/blog/2020-workshop-call-for-proposals.md
Documentation changes
[README](https://github.com/pythonindia/inpycon-blog/blob/master/README.md)
Updated the readme to include contribution instructions for writers and also updated the installation instructions.
Should we also use Tags and Summary for the blog metadata, or should I remove them?
=> Updated Readme

content/blog/2020-outreach-partners.md, content/blog/2020-pycon-india-mentorship.md, content/blog/2020-workshop-call-for-proposals.md
Updated the outreach partners blog to include new information
=> Updated the outreach partners blog

content/blog/2020-cfp-extension.md
=> Added the CFP extension blog

content/blog/2020-announce-ticket-sales.md
Tagging for detailed review as there are lot of terms and conditions involved  @inovizz @sayanchowdhury @satyakaam @palnabarun
=> Ticket Sales Starting Soon blog

content/blog/2020-announce-ticket-sales.md
- Changes all instances of going live to are live
- Removes extra whitespaces
- Fixes publish date
- Remove extra attribution at the end of blog post
=> Fix details in the ticket blog article

content/blog/2020-call-for-sponsors.md, content/blog/2020-convince-your-boss.md
- Updated slugs and filename for Call for Sponsors post 
- Updated date of publishing for both articles
=> [Hotfix] Update slug & published date

content/blog/2020-announcing-keynote-speaker-james.md
CC: @sayanchowdhury @palnabarun @vipulgupta2048
=> Added keynote speaker announcement for James Powell

content/blog/2020-announcing-keynote-speaker-anand.md
Signed-off-by: Sayan Chowdhury <sayan.chowdhury2012@gmail.com>
=> Announce S Anand as the Keynote Speaker

content/blog/2020-announcing-keynote-speaker-victor.md
Signed-off-by: Sayan Chowdhury <sayan.chowdhury2012@gmail.com>
=> Announce Victor as Keynote Speaker

content/blog/2020-announce-final-schedule.md
Blog post about announcing the schedule for PyCon India 2020
=> Announce 2020 schedule

content/blog/2020-workshop-devsprints-tickets.md
CC: @palnabarun @vipulgupta2048 @sayanchowdhury
=> Added ticket announcement blog for workshops and devsprints

content/blog/2020-workshop-devsprints-tickets.md
This fix coming in extra hot. 🔥 
Also tidied up a few more things along with `ruuning`. 
CC: @palnabarun
=> [Hotfix]fix the workshop and devsprint tickets blog content

content/blog/2020-announcing-epam-as-gold-sponsor.md
CC: @vipulgupta2048 @sayanchowdhury @palnabarun
=> Add sponsor blog for EPAM

content/blog/2020-announcing-toyota-connected-as-silver-sponsor.md
=> Add blog for Toyota Connected Sponsorship announcement

content/blog/2020-announcing-auth0-gold-sponsor.md
CC: @palnabarun @vipulgupta2048
=> Add sponsor blog for Auth0

content/blog/2020-announcing-redhat-silver-sponsor.md
CC: @palnabarun @vipulgupta2048
=> Add sponsor blog for Red Hat

content/blog/2020-announcing-github-silver-sponsor.md
=> Add GitHub as silver sponsor

content/blog/2020-announcing-microsoft-azure-platinum-sponsor.md
CC: @vipulgupta2048 @palnabarun
=> Add sponsor blog for Microsoft Azure

content/blog/2020-anouncing-keynote-speaker-terri.md
CC: @vipulgupta2048 @sayanchowdhury
=> Add keynote announcement for Terri Oda

content/blog/2020-announcing-pipal-academy-startup-sponsor.md
CC: @palnabarun @vipulgupta2048
=> Add sponsor blog for Pipal Academy

content/blog/2020-anouncing-keynote-speaker-terri.md
=> [Hotfix] Fix Speaker image size

content/blog/2020-announcing-de-shaw-platinum-sponsor.md
=> Update D. E. Shaw blog as per sponsor requirements

content/blog/2020-announcing-auth0-gold-sponsor.md
=> Update auth0 blog content

content/blog/2020/trying-something-new.md
=> Update .extend() announcement blog

content/blog/2020-announce-devsprints.md
=> What's different with PyCon India 2020 Devsprints

content/blog/2020-announcing-jetbrains-silver-sponsor.md
Solves https://github.com/pythonindia/inpycon2020-tasks/issues/85
=> Announce Jetbrains as Silver Sponsor

content/blog/2020/diversity-inclusion-track.md
=> Add diversity & inclusion post

CONTRIBUTING.md, themes/inpycon2020/templates/base.html
=> Update CoC link in 2020 theme and contributing guide

content/blog/2020/announce-pycon-india-program-guide.md
=> Add PPG blog

content/blog/2020/announce-video-release.md
=> Add release-videos blog

content/blog/2021/announcing-pycon-india.md
CC: @palnabarun @sayanchowdhury @chkumar246
=> Add PyCon India 2021 announcement blog

content/blog/2021/volunteering.md
CC: @palnabarun @sayanchowdhury
=> Add volunteering blog for 2021

content/blog/2021/announcing-pycon-india.md
CC: @chkumar246 @palnabarun @sayanchowdhury
=> Add updated dates to the 2021 announcement blog

content/blog/2021/conference-structure-update.md
CC: @palnabarun @sayanchowdhury @chkumar246
=> Add PyCon India 2021 dates update blog

content/blog/2021/cfp-announcement.md
CC: @palnabarun @chkumar246 @sayanchowdhury
=> Add PyCon India 2021 CFP announcement blog

content/blog/2021/outreach-partners.md
CC: @abhishekmishragithub @anistark
=> Add outreach partners blog for 2021

content/blog/2021/announcing-pycon-india.md
* Move the updated dates and structure to the top
* Add a link to the updates blog
CC: @chkumar246 @palnabarun
=> Update the PyCon India 2021 announcement blog

content/blog/2021/outreach-partners.md
=> Update the 2021 outreach partners blog

content/blog/2021/cff-best-practises.md
=> Add CFP best practises blog

content/blog/2021/cff-best-practices.md
=> Convert practise --> practice

content/blog/2021/cfp-extension.md
CC: @chkumar246 @vipulgupta2048
=> Add 2021 cfp extension blog

content/blog/2021/pyflames.md
CC: @raukadah @RiteshAgrawal 
Please comment the website links for any communities I've missed. 
Also, http://pune.python.org.in/ and http://bangalore.python.org.in/ are down.
=> Add PyFlames 2021 blog

content/blog/2021/announcing-tickets.md
=> Add 2021 ticket announcement blog

content/blog/2021/cfp_help.md
=> Fix typo in Mentorship blog #368

content/blog/2021/bof-poster-cfp.md
=> Add BoF and poster presentation CFP blog

content/blog/2021/announcing-keynote-speaker-alolita.md
=> Add Keynote announcement blog for Alolita Sharma

content/blog/2021/announcing-keynote-speaker-sebastian.md
=> Add Sebastián Ramírez keynote speaker blog

content/blog/2021/announcing-keynote-speaker-alolita.md, content/blog/2021/announcing-keynote-speaker-sebastian.md, content/blog/2021/announcing-tickets.md, content/blog/2021/cfp-extension.md
=> Patch keynote speakers image URL 

content/blog/2021/announcing-in-kind-sponsorship.md
=> Add In-Kind sponsors blog

content/blog/2021/announcing-keynote-speaker-ajith-kumar.md
=> Add Keynote speaker blog for Dr. AJith Kumar

content/blog/2021/announcing-keynote-speaker-ajith-kumar.md
Signed-off-by: Chandan Kumar (raukadah) <raukadah@gmail.com>
=> Added ticket link in Ajith Keynote blog

themes/inpycon2021/static/css/blog-style.css
Fixes issues from https://github.com/pythonindia/inpycon-blog/pull/377#issuecomment-868210911
=> fix issues with paginator in 2021 theme

content/blog/2021/announcing-keynote-speaker-ajith-kumar.md, themes/inpycon2021/static/css/blog-style.css, themes/inpycon2021/templates/components/pagination.html
=> fix keynote announcement image

content/blog/2021/announcing-keynote-speaker-luciano.md
=> Add Luciano Ramalho keynote speaker blog

content/blog/2021/2021-announce-final-schedule.md, pelicanconf.py
=> Add PyCon India 2021 Schedule Announcement blog

content/blog/2021/pyflames_v2.md
CC: @palnabarun @RiteshAgrawal @raukadah
=> Add PyFlames v2 blog

content/blog/2021/announcing-inkind-sponsors-second.md
CC: @vipulgupta2048 @raukadah @anistark
=> Add 2nd blog for inkind sponsors

content/blog/2021/announcing-inkind-sponsors-first.md
CC: @raukadah @anistark @vipulgupta2048
=> Fix the Inkind sponsors announcement blog's title

themes/inpycon2021/templates/components/footer.html
=> Fix Social Media links in Footer

content/blog/2021/birds-of-feather.md, content/blog/2021/cs-education-panel-discussion.md, content/blog/2021/python-in-space-panel-discussion.md
=> Add bof & panel discussion blogs

content/blog/2021/workshops.md, themes/inpycon2021/static/css/style.css
=> Add 2021/workshops blog post

content/blog/2021/cs-education-panel-discussion.md, content/blog/2021/diversity-in-cybersecurity-panel-discussion.md
CC: @raukadah @vipulgupta2048 @sukanyamandal
=> Add cybersecurity panel discussion blog

content/blog/2021/2021-extend-track-schedule.md, content/blog/2021/diversity-in-cybersecurity-panel-discussion.md, content/blog/2021/neurodiversity.md
=> Neurodiversity and Experience Sharing Sessions

content/blog/2021/poster-presentation-sessions.md
@raukadah @Sc0rpi0n101 I was already working on the blog right now. Just later realised that the blog has already been merged and published already. The best thing to do in this situation is to atleast tag the issue to mention that someone else is working on it or there is PR to resolve it. The blog PR #402 has issues hence this PR.
Corrections include:
1. Removing unnecessary line breaks and word spacings.
2. Improving sentence structure
3. Removing unnecessary headings for a list. (check below)
4. And, more
Resolves: #401 
=> Corrections to poster sessions blog

content/blog/2021/cs-education-panel-discussion.md, content/blog/2021/python-in-space-panel-discussion.md
=> Speaker info updates

themes/inpycon2021/templates/components/footer.html, themes/inpycon2021/templates/components/header.html
Signed-off-by: Shashank Kumar (realslimshanky) <abc@shanky.xyz>
'Book ticket' -> 'Get the Program Guide'
=> [themes/inpycon2021] Removing 'Book ticket'

content/blog/2023/2023_guide_to_speaking.md
=> blog: Guide to Speaking at PyCon India

content/blog/2023/announcing-devsprints.md, content/blog/2023/venue-announcement.md
=> Devsprint 2023

content/blog/2023/announcing-devsprints.md
Fix date in Devsprints description
=> Update date in announcing-devsprints.md

content/blog/2023/inclusivity.md
=> Fix formatting in new tracks

content/blog/2023/announcing-devsprints.md
Update announcing-devsprints.md
=> Update Devsprints blog

content/blog/2024/keynote-announcement-mars-lee.md
=> Adds keynote blog for Mars Lee

content/blog/2024/Panel Discussions at PyCon India 2024
=> Create Panel Discussions at PyCon India 2024
